### ISSUE TITLE
Multinetwork tests failing due to upstream PowerModels change

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/ThreePhasePowerModels.jl#107]
Due to a change to `check_branch_directions` in lanl-ansi/PowerModels.jl#418, tests in `tp_multinetwork.jl` now fail. Update after new version of PowerModels.jl is tagged.

**Comment by ccoffrin** [comment]
Can you show me the kind of error it is generating?  I was hoping that would be a non-breaking change.

**Comment by pseudocubic** [comment]
For example, on `test\test_multinetwork.jl:15-16` the value you are comparing to is -0.012, but now that value comes out as around 1.2e-5 (I don't have the exact number in front of me, but it is definitely that magnitude). I didn't do an exhaustive comparison between the result of `parse_file` in v0.8.8 and on master, but I noted that the `b_to` and `b_fr` values become asymmetric on branch "6" when using PowerModels master.

**Comment by ccoffrin** [comment]
The near term fix is to relax the tests in this package so they pass with the current tagged version and master of PowerModels.

I have added this issue to mitigate the problem in the future, https://github.com/lanl-ansi/PowerModels.jl/issues/420.
