### ISSUE TITLE
PV Generators

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/ThreePhasePowerModels.jl#11]
Specification TBD.

**Comment by frederikgeth** [comment]
In OpenDSS there already is a model defined [here](https://github.com/tshort/OpenDSS/blob/master/Doc/OpenDSS%20PVSystem%20Model.doc). This model definition has not been copied to the main OpenDSS manual, but it is actually supported. I've tested parsing it in 6d66b4749c851202b4a14b2620133209e8d385cd. 

Where do you want to go with this?

**Comment by ccoffrin** [comment]
The primary goal of this issue is to figure out how we should support these in a generic way, in this package and PowerModels in general.  Once that is clear, it should be easy to parse various formats into the internal specification.

The very rough idea I have in mind is that both generators and loads should be generalized into dispatch-able and non-dispatch-able variants; probably at the PowerModels level.  Similar to dispatch-able generators dispatch-able loads should probably have cost functions associated with them.  In this case, PV and Wind will both be examples of a generic non-dispatch-able generator; demand responce would be an example of a dispatch-able load.

One open question is my mind is how to best support components that are only partially dispatch-able.  My feeling is that these should be broken into separate dispatch-able and non-dispatch-able components, I just want to check that does not have some unforeseen negative side-effects.

A hack that _might_ work in the near term is to set the upper and lower bounds on a generator to the same value.  Have you explored that option?

**Comment by frederikgeth** [comment]
I will explore this again next week. Setting the bounds like you propose does indeed work.
