### ISSUE TITLE
Issue with Zb calculation

### ISSUE THREAD

**Issue by kdheepak** [lanl-ansi/ThreePhasePowerModels.jl#114]
cc @risjain

If `baseMVA` is three phase, then it should be divided by three. I believe this line should be modified.

https://github.com/lanl-ansi/ThreePhasePowerModels.jl/blob/848b6e9c56011ab0e22f4229a50cda008a8e568a/src/io/opendss.jl#L527

This is the equation to calculate Zbase:

```
Zbase = (basekv / sqrt(3))^2 / baseMVA_perphase # OR

Zbase = (basekv / sqrt(3))^2 / ( baseMVA_nphase / nconductors ) # i.e.

Zbase = (basekv / sqrt(3))^2  * nconductors / ( baseMVA_nphase )
```

If you remove the ` * nconductors` subexpression, you'll get the right values for rmatrix, xmatrix in per unit without multiplying by 3 in the following lines:

https://github.com/lanl-ansi/ThreePhasePowerModels.jl/blob/848b6e9c56011ab0e22f4229a50cda008a8e568a/src/io/opendss.jl#L524-L525

**Comment by kdheepak** [comment]
See equation for this by @risjain:

![z_base](https://user-images.githubusercontent.com/1813121/53130085-8bae5c00-3526-11e9-82c1-4b19b0b5ed54.png)

**Comment by pseudocubic** [comment]
@frederikgeth do you have any comments?

**Comment by frederikgeth** [comment]
This indeed resolves the confusion. I have to give credit to @sanderclaeys as well, he independently figured this out at pretty much the same time. Thanks guys!

**Comment by kdheepak** [comment]
Awesome!

**Comment by sanderclaeys** [comment]
To be sure, we do need the factor of 3 in the current implementation to get the right solutions; I noticed the same when working on the transformer extension. This is my understanding of the issue:

With the current per-unit conversion, you choose the line-to-line voltage as a voltage base. Nothing wrong with that in itself, you can choose any base you want. However, further on in the code, you add the voltage magnitude constraint on the type 3 bus, and fix it at 1. So implicitly, you fix the magnitude at the line-to-line voltage, a factor of sqrt(3) higher than the line-to-neutral voltage. This will lead to less losses, as the network is less lossy at a higher voltage. To compensate for this, you need to multiply your impedances by a factor of 3 (hence the factor needed for consistency with OpenDSS).

So there are two options
1. Fix the voltage magnitude at 1/sqrt(3). However, this would imply also rescaling the voltage bounds, so not the most desirable fix.
2. Use the phase-to-neutral as a voltage base to nondimensionalize the impedances. This is what you do implicitly right now with the factor of 3.
