### ISSUE TITLE
JSON parser

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/ThreePhasePowerModels.jl#120]
Need to add a parser to support saving as json and re-importing (due to `MultiConductorVector` and `MultiConductorMatrix`), specifically for the upcoming features in #117

**Comment by ccoffrin** [comment]
Given that those data structures are implemented in PowerModels, we should probably put this parser in that package.

**Comment by pseudocubic** [comment]
There will still need to be extensions here for structures unsupported by PowerModels (see #117 ), description edited

**Comment by ccoffrin** [comment]
Good point!  One option is to make the JSON serialization more structural.  For example, right now `MultiVector([1,2,3])` goes to `[1,2,3]` in JSON.  However, if we instead do `{"multivector"=true, "value"=[1,2,3]}` then you can develop a fairly generic JSON reader that may not need to know about any the extensions of any particular package.

**Comment by ccoffrin** [comment]
@pseudocubic, can you confirm that the new JSON parser is PowerModels master is working in this context before we tag the next PowerModels version?

**Comment by pseudocubic** [comment]
I can confirm that `PowerModels.parse_json` works with ThreePhasePowerModels master (with `validate=false`). 

The problem with `validation=true` is that in our opendss parser when I instantiate the sourcegen, no `vg` is given, which is expected during `check_voltage_setpoints`, so that's a problem on this end.
