### ISSUE TITLE
NFAPowerModel for transformers

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/ThreePhasePowerModels.jl#133]
We need to add support for the `NFAPowerModel` to:

`constraint_tp_trans_flow`

**Comment by ccoffrin** [comment]
It can he treated similarly to a branch, if that helps.

**Comment by sanderclaeys** [comment]
I will have a look at this later on. It is not as trivial as it might seem, because the configuration of the winding affects which phase on one side is routed to which phase on the other side.

**Comment by ccoffrin** [comment]
@pseudocubic can we close this?
