### ISSUE TITLE
matlab parser changes?

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/ThreePhasePowerModels.jl#40]
@ccoffrin 

I think we are leaving out a way to specify the line charging susceptance for each phase on branches. Should we adopt the matpower convention and use one number `br_b` and split the value as we do in PowerModels?

Also, I might suggest reordering the fields so that the upper triangular `r` matrix and `x` matrix elements are grouped, instead of alternating.

Finally, I think we need to add `tap` and `shift` to branches now, so we don't have to change this later.

Thoughts?

**Comment by ccoffrin** [comment]
Regarding the line charging, it's not clear to me what level of detail is really necessary here, so lets ask @frederikgeth and @hakanergun for guidance on this.

I can see pros and cons to both parameter organizations.  I was inclined to put them together because a common error is that the ratio of r/x is off.  Were you running into an issue that would motivate the change?

Re tap and shift, I would omit these for now.  If we eventually add transformers to this data format I think there is a strong case that they will be a separate data block, even if they become branches internally.

**Comment by pseudocubic** [comment]
In my experience with OpenDSS, only a single value for line charging is specified for the branch, and `g_fr/to` can't be derived at all (so far as I can tell). If this is the most commonly used data format in distribution systems then I think specifying `br_b` for each phase might be good enough. But if @frederikgeth and @hakanergun think if would be nice to have the increased detail it could be worth it.

No, there is no problem with parameter organization, I just thought it would be easier to input matrices one at a time, instead of switching back and forth, but I had not thought about the case where you would want to get the ratio right when constructing them. 

That sounds fine to me then, I wasn't sure how closely we wanted to use matpower-like conventions, but a separate data block for transformers would work well for me.

**Comment by frederikgeth** [comment]
Line charging susceptance can be safely ignored in the context of low-voltage and medium-voltage for overhead lines and cables which are not too long and not too lightly loaded, cfr Kersting [1] Chapter 5. So it's generally good enough. However, I quote part of the conclusions there: 

> When the analysis is being done using a computer, the approach to take is to go ahead and model the shunt admittance for both overhead and underground lines. Why make a simplifying assumption when it is not necessary?

I'm in favor for having separate branch and transformer data blocks (not the matpower approach), although they could be unified underneath. Expect lots of different transformer model variants as well (delta/wye + vector group + earthing configuration). For a unification reference, check out [2]. In this context, shunt conductance is useful to model transformer no-load losses (which aren't neglegible for distribution transformers). 

So there are two main things to consider:
- Compatibility with OpenDSS, the de-facto research format for modeling grids with phase unbalance
- Having a mathematical model standardised on a pi-section supporting asymmetric shunt admittance

I feel that it should be possible to use the extensions approach with the .m files to obtain case definitions identical to those of OpenDSS. But I'd say matpower backward compatibility isn't a primary concern. So .m files don't need to be able to instantiate all possible mathematical parameters underneath, i.e. it's enough to define `br_b` for each phase, and divide by 2 to obtain the equivalent asymmetric shunt value. Users that realize they want asymmetrical shunts (e.g. to parameterize a T model) in the near term should be able to script this / use JSON? 

I think I prefer the interleaved r-x approach as it is now over add r-s and x-es put together.

[1] Kersting, W. H. (2001). Distribution System Modeling and Analysis. (L. Grigsby, Ed.). Boca Raton, FL: CRC Press.
[2] Moorthy, S. S., & Hoadley, D. (2002). A new phase-coordinate transformer model for Ybus analysis. IEEE Trans. Power Syst., 17(4), 951–956. https://doi.org/10.1109/TPWRS.2002.804996

**Comment by ccoffrin** [comment]
Very helpful, suggestions thanks!
