### ISSUE TITLE
Support line lengths (incl. units)

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/ThreePhasePowerModels.jl#43]
Add support to OpenDSS parser for non-default (`length=1`, `units=none`) line lengths

**Comment by ccoffrin** [comment]
Based on my very preliminary experience with UnitFul, I would discourage making it a requirement in the core package; but I am open to discussion of that point.

**Comment by pseudocubic** [comment]
It wasn't high on my list so I didn't have a specific time frame in mind, but if its a feature that's needed I can work on it later this week. I agree that it would be better to avoid added the dependency, especially since this is only lengths, so conversions between them should be trivial.

**Comment by frederikgeth** [comment]
As it looks now, I may look into parsing an OpenDSS case that depends on the lengths being read beginning of next week. The units the case uses are km and m.

**Comment by pseudocubic** [comment]
See PR #46

I still need to add some unit tests before it gets merged, but the functionality should be there.
