### ISSUE TITLE
Calculation of (series) admittance from impedance matrix

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/ThreePhasePowerModels.jl#45]
I'm not familiar enough with Julia's syntax to understand what is really going on [here](https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/data.jl#L66), but it seems it doesn't calculate the matrix inverse in case of a the impedance being a matrix. 

I ran into this after I observed that the line active power losses in the AC polar formulation were negative for all phases, which is physically impossible. I'm not sure how the fix should look like, but with a quick and dirty fix does get rid of the negative line losses.

**Comment by ccoffrin** [comment]
Assuming you have a matrix `Z`, I presumed that `Y = 1/Z` on an item by item basis.  Is that correct?

**Comment by ccoffrin** [comment]
All of the fancy Julia is just to do item-by-item computation that works on a both a matrix or an non-matrix element.

**Comment by frederikgeth** [comment]
I'm pretty confident that it should be a matrix inverse, e.g. as discussed [here](https://en.wikipedia.org/wiki/Zbus) for a slightly different contex.

**Comment by ccoffrin** [comment]
In that case `calc_branch_y` should be updated to the correct semantics.
