### ISSUE TITLE
Simple Tranformers

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/ThreePhasePowerModels.jl#7]
Specification TBD.

**Comment by bluejuniper** [comment]
Not sure if this deserves to be a new issue, but it looks like the dictionary structures currently used to parse component parameters is not compatible with the wdg=1 ... params1 ... wdg=2 ... params2 format for transformers on page 120 of the opendss manual. Will still work with the alternate array method for setting parameters on page 121

**Comment by pseudocubic** [comment]
The current parser should be compatible with that, can you provide me an example where it doesn't work right so I can debug it?

**Comment by frederikgeth** [comment]
What is the use-case / requirements? A perfectly grounded wye-wye transformer (YNyn) with vector group 0 and an ideal voltage magnitude transformation shouldn't take much time to implement for all formulations. Any specific unbalanced IEEE test cases for which the transformer models should be derived first?
