### ISSUE TITLE
mismatch units dss parser

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/ThreePhasePowerModels.jl#90]
For example, the dss input file might contain the following two lines

New LineCode.4c_70 nphases=3 R1=0.446 X1=0.071 R0=1.505 X0=0.083 C1=0 C0=0 Units=km
New Line.LINE1 Bus1=1 Bus2=2 phases=3 Linecode=4c_70 Length=1.098 Units=m

Both the parsed line and linecode dicts will then contain a "units" property. On line 412 of opendss.jl, the line and linecode dicts are merged, resulting in the loss of the "units" of the line. If the units are not the same, this leads to an error in the modelling. This issue is marked with a TODO in the createLine function at line 177 of dss_structs.jl. Inside the createLine function however, the input data no longer contains the data needed to solve this issue.

**Comment by pseudocubic** [comment]
In `dss_structs.jl` the intended behavior is that all units are converted to meters for both lines and linecodes. This is actually what OpenDSS seems to do as well. The TODO you reference must be left over from before this behavior was added. 

From my testing it seems this behavior is working as expected. `merge!(createLine, createLinecode)` converts your example above to the same values that OpenDSS does:

```
> Dict{String,Any} with 39 entries:
  "b1"         => 0.0
  "c1"         => 0.0
  "repair"     => 3.0
  "x0"         => 8.3e-5
  "earthmodel" => ""
  "bus2"       => "Primary"
  "cmatrix"    => [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]
  "length"     => 1.098
  "name"       => "4c_70"
  "bus1"       => "sourcebus"
  "nphases"    => 3
  "faultrate"  => 0.1
  "geometry"   => ""
  "switch"     => false
  "cncables"   => ""
  "basefreq"   => 60.0
  "xg"         => 0.155081
  "phases"     => 3
  "rmatrix"    => [0.000799 0.000353 0.000353; 0.000353 0.000799 0.000353; 0.000353 0.000353 0.000799]
  "emergamps"  => 600.0
  "spacing"    => ""
  "rho"        => 100.0
  "freq"       => 60.0
  "units"      => "m"
  "neutral"    => 3
  "x1"         => 7.1e-5
  "r1"         => 0.000446
  "xmatrix"    => [7.5e-5 4.0e-6 4.0e-6; 4.0e-6 7.5e-5 4.0e-6; 4.0e-6 4.0e-6 7.5e-5]
  "rg"         => 0.01805
  "tscables"   => ""
  "b0"         => 0.0
  "r0"         => 0.001505
  "kron"       => false
  "c0"         => 0.0
  "enabled"    => true
  "linecode"   => "4c_70"
  "normamps"   => 400.0
  "pctperm"    => 20.0
  "wires"      => ""

```
 Can you provide an example where it is more clearly broken? Maybe this example is not complex enough and I'm just having trouble finding the issue.
